### ISSUE TITLE
RewindState seems not correct. 

### ISSUE THREAD

**Issue by RickyYCheng** [adammyhre/Unity-Multiplayer-Kart#5]
First, appreciate for this awesome repository. :)

---

In line 325's function: https://github.com/adammyhre/Unity-Multiplayer-Kart/blob/master/Assets/_Project/Scripts/KartController.cs#L325, the reconciliation. 

We've got 
```cs
StatePayload rewindState = IsHost ? serverStateBuffer.Get(bufferIndex - 1) : lastServerState; // Host RPCs execute immediately, so we can use the last server state
StatePayload clientState = IsHost ? clientStateBuffer.Get(bufferIndex - 1) : clientStateBuffer.Get(bufferIndex);
```

You commented `// Host RPCs execute immediately, so we can use the last server state`, and I am pretty sure this comment means that if `IsHost` is true, we use `lastServerState` as the `rewindState`. But it seems that the expression here is reversed. 
Should we just use `var rewindState = IsHost ? lastServerState ?serverStateBuffer.Get(bufferIndex - 1); ` ?

---
And I do not really know why we minus 1 to bufferIndex here: `serverStateBuffer.Get(bufferIndex - 1)` ? 
Why do not we just use `serverStateBuffer.Get(bufferIndex)` here?

Ticks | 0 | 1 | 2 | 3 | 4 | 5 | 6
-- | -- | -- | -- | -- | -- | -- | --
Client Input Buffer | i0 | i1 | i2 | i3 | i4 | i5 | i6
Client State Buffer | cs0 | cs1 | cs2 | cs3 | cs4 | cs5 | cs6
Received Server State |   |   |   |   | ss0 |   | ss1
Server State Buffer |   |   | ss0 | ss1 | ss2 |   | ss3
Received Input |   |   | i0 | i1 | i2 |   | i3

Consider the tick 6 here on the figure. If we use minus 1, we compare the difference on cs2 and ss0. It seems make no sense.

**Comment by adammyhre** [comment]
You're touching on a topic we've investigated in a past issue. There, we explored why, as the host, we tap into the latest server buffer state, leveraging the immediate update hosts have. Yet, due to how `HandleClientTick()`, `HandleServerReconciliation()`, and `HandleServerTick()` queue up, we end up with a bit of a timing mismatch between the server and client state buffers. This causes the host's comparisons to be slightly out of sync, and so another commit was applied to correct this.

For more context, check out the previously closed issue here: [Issue Link](https://github.com/adammyhre/Unity-Multiplayer-Kart/issues/2).
